services:
  pocketbase:
    build: .
    container_name: ${PB_NAME}
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - /var/lib/docker/volumes/${PB_NAME}/pb_data:/pb/pb_data
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/api/health || exit 1
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  pb_data:
    name: ${PB_NAME}_data
